# 定义 EV_spatalk 类
setClass("EV_spatalk",
         slots = c(database = "data.frame",
                   all.cell.type = "character",
                   s.cell.type = "character",
                   Sender.celltype.id = "character",
                   Receiver.celltype.id = "character",
                   Sender.spot.id = "character",
                   Receiver.spot.id = "character",
                   Distance.corr.LR.results = "data.frame",
                   EVrelease.corr.LR.results = "data.frame",
                   inter.LR.results = "list",
                   all.can.LR.id = "character",
                   st.seurat.obj = "Seurat",
                   sc.seurat.obj = "Seurat",
                   all.spot.module.score = "data.frame",
                   distance.results = "data.frame",
                   neighborhood.results = "list",
                   metadata = "data.frame",
                   interaction_df = "data.frame",
                   interaction_df_raw.indensity = "data.frame",
                   modules = "array",
                   db_mac = "list",
                   db_tcell = "list",
                   nnls_bin = "character",
                   nearest.spot.list = "list",
                   all.nitch.LR.talk.list = "list",
                   all.spot.lr_interaction = "list",
                   sender.spot.lr_interaction = "list",
                   spot.LR.freq.results = "data.frame",
                   LR.in.spot.frequency_table = "data.frame",
                   LR.in.spot.RRA.results = "data.frame",
                   EV_spatalk_stat_results = "data.frame"))


